{{- include "ffc-helm-library.container-secret" (list . "mcu-techspike-ai-web.container-secret") -}}
{{- define "mcu-techspike-ai-web.container-secret" -}}
stringData:
  {{- if .Values.appInsights.connectionString }}
  APPINSIGHTS_CONNECTIONSTRING: {{ quote .Values.appInsights.connectionString }}
  {{- end }}
{{- end -}}
