{{- include "ffc-helm-library.container-secret" (list . "mcu-techspike-ai-web.container-secret") -}}
{{- define "mcu-techspike-ai-web.container-secret" -}}
stringData:
  {{- if .Values.appInsights.connectionString }}
  APPINSIGHTS_CONNECTIONSTRING: {{ quote .Values.appInsights.connectionString }}
  {{- end }}
  AZURE_STORAGE_MCU_ACCOUNT_NAME: {{ .Values.container.mcuStorageAccountName }}
  AZURE_STORAGE_MCU_CONNECTION_STRING: {{ .Values.container.mcuStorageConnectionString }}
  AZUREID_CLIENT_SECRET: {{ quote .Values.azureAppRegistration.clientSecret }}
  AZUREID_CLIENT_ID: {{ quote .Values.azureAppRegistration.clientId }}
  AZUREID_TENANT_ID: {{ quote .Values.azureAppRegistration.tenantId }}
  COOKIE_PASSWORD: {{ quote .Values.container.cookiePassword }}
  OPEN_AI_ENDPOINT: {{ quote .Values.container.openAiEndpoint }}
  OPEN_AI_KEY: {{ quote .Values.container.openAiKey }}
  OPEN_AI_DEPLOYMENT_ID: {{ quote .Values.container.openAiDeploymentId }}
  TEXT_ANALYTICS_ENDPOINT: {{ quote .Values.container.textAnalyticsEndpoint }}
  TEXT_ANALYTICS_KEY: {{ quote .Values.container.textAnalyticsKey }}
  SEARCH_ENDPOINT: {{ quote .Values.container.searchEndpoint }}
  SEARCH_KEY: {{ quote .Values.container.searchKey }}
  SEARCH_INDEX: {{ quote .Values.container.searchIndex }}
{{- end -}}
