{{- include "adp-helm-library.deployment" (list . "mcu-techspike-ai-web.deployment") -}}
{{- define "mcu-techspike-ai-web.deployment" -}}
spec:
  template:
    spec:
      containers:
      - {{ include "adp-helm-library.container" (list . "mcu-techspike-ai-web.container") }}
{{- end -}}
