storageAccounts:
  - name: 'mcutchspk'
    tables: 
      - name: 'documents'
        roleAssignments:
          - roleName: 'TableDataContributor'
      - name: 'prompts'
        roleAssignments:
          - roleName: 'TableDataContributor'
