- key: APPINSIGHTS_CONNECTIONSTRING
  value: "{{servicename}}-APPINSIGHTS-CONNECTIONSTRING"
  type: "keyvault"
- key: AUTHENTICATION_ENABLED
  value: "false"
- key: AZURE_STORAGE_MCU_ACCOUNT_NAME
  value: "sndadpinfst3401mcutchspk"
- key: OPEN_AI_DEPLOYMENT_ID
  value: "{{servicename}}-container-openaideploymentid"
  type: "keyvault"
- key: OPEN_AI_ENDPOINT
  value: "{{servicename}}-container-openaiendpoint"
  type: "keyvault"
- key: OPEN_AI_API_KEY
  value: "{{servicename}}-container-openaikey"
  type: "keyvault"
- key: SEARCH_ENDPOINT
  value: "{{servicename}}-container-searchendpoint"
  type: "keyvault"
- key: SEARCH_KEY
  value: "{{servicename}}-container-searchkey"
  type: "keyvault"
- key: SEARCH_INDEX
  value: "{{servicename}}-container-searchindex"
  type: "keyvault"
- key: TEXT_ANALYTICS_ENDPOINT
  value: "test"
- key: TEXT_ANALYTICS_API_KEY
  value: "test"
