- key: NODE_ENV
  value: "production"
- key: PORT
  value: "3000"
- key: APPINSIGHTS_CLOUDROLE
  value: "{{serviceName}}"  
- key: container.mcuStorageAccountName
  value: "mcu-techspike-ai-web"  
- key: container.mcuStorageConnectionString
  value: "{{servicename}}-container-mcuStorageConnectionString"
  type: "keyvault"
- key: container.openAiDeploymentId
  value: "{{servicename}}-container-openaideploymentid"
  type: "keyvault"
- key: container.openAiEndpoint
  value: "{{servicename}}-container-openaiendpoint"
  type: "keyvault"
- key: container.openAiKey
  value: "{{servicename}}-container-openaikey"
  type: "keyvault"
- key: container.searchEndpoint
  value: "{{servicename}}-container-searchendpoint"
  type: "keyvault"
- key: container.searchKey
  value: "{{servicename}}-container-searchkey"
  type: "keyvault"
- key: container.searchIndex
  value: "{{servicename}}-container-searchindex"
  type: "keyvault"
- key: container.textAnalyticsEndpoint
  value: "{{servicename}}-container-textanalyticsendpoint"
  type: "keyvault"
- key: container.searchEndpoint
  value: "{{servicename}}-container-searchendpoint"
  type: "keyvault"