environment: production
environmentCode:
name: mcu-techspike-ai-web
namespace: mcu-techspike
workstream: mcu-techspike
image: mcu-techspike-ai-web

labels:
  component: service

appInsights:
  connectionString:

containerConfigMap:
  name: mcu-techspike-ai-web-config-map

containerSecret:
  name: mcu-techspike-ai-web-container-secret
  type: Opaque

deployment: {}

container:
  requestMemory: 100Mi
  requestCpu: 100m
  limitMemory: 100Mi
  limitCpu: 100m
  port: 3000

livenessProbe:
  path: /healthz
  port: 3000
  initialDelaySeconds: 20
  periodSeconds: 10
  failureThreshold: 3
  timeoutSeconds: 5

readinessProbe:
  path: /healthy
  port: 3000
  initialDelaySeconds: 30
  periodSeconds: 10
  failureThreshold: 3
  timeoutSeconds: 5
